# Site settings
title: "Rodrigo Scomação do Nascimento"
email: rodrigo.sc.na@gmail.com
description: "A technology enthusiast in an eternal quest for knowledge."
baseurl: ""
url: "http://rodrigosn.com"
